###########
# site.title

title:    'Columbia PILF'
subtitle: 'Public Interest Law Foundation'

## note:
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
#    note: for root path use empty string e.g. '' - do NOT include trailing slash e.g. /

path:  ''
url:   'http://columbia-pilf.github.io'


#########################
# more settings

markdown: kramdown

exclude: ['README.md']

defaults:
  - scope:
      path: ""
      type: tabs
    values:
      layout: default

collections:
  tabs:
    output: true
    permalink: /:path/
